build(package): install zod@3 to type payloadSchema
https://github.com/novuhq/novu/issues/9416

TypeScript error when using zod@4:

```
src/novu/workflows.ts:14:52 - error TS2339: Property 'name' does not exist on type 'never'.

14         body: `This is a test email from ${payload.name}!`,
                                                      ~~~~

Found 1 error in src/novu/workflows.ts:14
```